const mightInterstYouPillItemList = [
  { id: 1, title: "iPhone 15" },
  { id: 2, title: "Flo" },
  { id: 3, title: "Watsons" },
  { id: 4, title: "GS Store" },
  { id: 5, title: "Airfryer" },
  { id: 6, title: "Dyson Süpürge" },
  { id: 7, title: "Stanley Termos" },
  { id: 8, title: "Koltuk Takımı" },
  { id: 9, title: "Kurutma Makinesi" },
  { id: 10, title: "Playstation 5" },
  { id: 11, title: "Kuzine Soba" },
  { id: 12, title: "Aura Cleanmax" },
  { id: 13, title: "Arçelik Bulaşık Makinesi" },
  { id: 14, title: "Pandora" },
  { id: 15, title: "Zara" },
  { id: 16, title: "Sweatshirt" },
  { id: 17, title: "Philips Airfryer" },
  { id: 18, title: "Decathlon" },
  { id: 19, title: "IKEA" },
  { id: 20, title: "Siemens Bulaşık Makinesi" },
  { id: 21, title: "Gant" },
  { id: 22, title: "Under Armour" },
  { id: 23, title: "Bambi Yatak" },
  { id: 24, title: "Baget Yüzük" },
  { id: 25, title: "Adidas Samba" },
  { id: 26, title: "Atasay" },
  { id: 27, title: "Bargello" },
  { id: 28, title: "Cep Telefonu" },
  { id: 29, title: "UGG" },
  { id: 30, title: "Nike Air Force" },
];

export default mightInterstYouPillItemList;
