const popularLinkItemList = [
  {
    title: "Popüler Marka ve Mağazalar",
    items: [
      "Penti",
      "Mango",
      "Vivense",
      "Watsons",
      "English Home",
      "Bershka",
      "Stradivarius",
      "The North Face",
      "Beymen",
      "Columbia",
      "Samsung",
      "Lumberjack",
      "Puma",
      "Mudo",
      "Derimod",
      "Apple",
      "New Balance",
      "Huawei",
      "Xiaomi",
      "Oppo",
      "Monster Notebook",
      "Birkenstock",
      "Arçelik",
      "DYSON",
      "Adidas",
      "Nike",
      "Skechers",
      "Lacoste",
      "Avva",
      "Under Armour",
      "Madame Coco",
      "Pull & Bear",
      "Koton",
      "Defacto",
      "Mavi",
      "Pierre Cardin",
      "Tchibo",
      "Farmasi",
      "Helly Hansen",
      "Network",
      "Bosch",
      "Karaca",
      "Kiğılı",
      "Migros",
      "CAT",
    ],
  },
  {
    title: "Popüler Sayfalar",
    items: [
      "Bluetooth Kulaklık",
      "iPhone",
      "Samsung Cep Telefonu",
      "Azerbaycan'dan Alışveriş",
      "Nike Air Max",
      "Robot Süpürge",
      "Laptop",
      "iPhone 15",
      "Soba & Isıtıcı",
      "iPhone 15 Plus",
      "iPhone 15 Pro",
      "iPhone 15 Pro Max",
      "Apple Watch",
      "Çamaşır Makinesi",
      "Bulaşık Makinesi",
      "Buzdolabı",
      "Öğrencilere Vergisiz Telefon",
      "Öğrencilere Vergisiz Laptop",
      "E-İhracat",
      "Sırt Çantası",
      "Apple Watch Series 9",
      "Termos",
      "Kadın Mont",
      "Erkek Mont",
      "Sınav Hazırlık ve Test Kitapları",
      "Televizyon",
      "Kahve Makinesi",
      "Kitap",
      "Sneaker",
      "Oyuncu Koltuğu",
      "Elbise",
      "Popüler Aramalar",
      "Popüler Kategoriler",
      "Dyson Airwrap",
      "Apple Airpods",
      "Roman, Hikaye ve Edebiyat Kitapları",
      "Trendyol Blog",
      "Markalar",
      "Macbook",
      "Trendyol Romanian",
      "Trendyol Czech",
      "Trendyol English",
      "Trendyol Slovak",
      "Trendyol Arabic",
      "Trendyol Deutsch",
    ],
  },
];

export default popularLinkItemList;
